import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#f4f1ea',
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111',
    marginBottom: 10,
    marginTop: 10,
  },
  searchBox: {
    height: 40,
    borderWidth: 1,
    borderColor: '#999',
    borderRadius: 8,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    marginBottom: 20,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    marginLeft: 12,
    color: '#111',
  },
  input: {
    height: 40,
    borderWidth: 1,
    borderColor: '#999',
    borderRadius: 8,
    backgroundColor: '#fff',
    paddingHorizontal: 15,
    fontSize: 15,
    color: '#111',
    marginBottom: 22,
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
    marginTop: 5,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    marginLeft: 10,
    color: '#111',
  },
  calendarCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 24,
    marginBottom: 25,
  },
  monthRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  monthText: {
    fontSize: 19,
    fontWeight: '700',
    color: '#0B73D9',
  },
  arrowRow: {
    flexDirection: 'row',
  },
  arrowCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#e5e5e5',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  weekRow: {
    flexDirection: 'row',
    marginTop: 30,
    marginBottom: 18,
  },
  weekText: {
    width: '14.28%',
    textAlign: 'center',
    fontSize: 15,
    color: '#2F80ED',
  },
  dateGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  dateText: {
    width: '14.28%',
    height: 42,
    textAlign: 'center',
    fontSize: 18,
    color: '#333',
  },
  oldDate: {
    width: '14.28%',
    height: 42,
    textAlign: 'center',
    fontSize: 18,
    color: '#aaa',
  },
  timeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  timeButton: {
    width: '30%',
    height: 30,
    borderWidth: 1,
    borderColor: '#aaa',
    borderRadius: 9,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  activeTimeButton: {
    backgroundColor: '#69B2F5',
    borderColor: '#007AFF',
  },
  timeText: {
    fontSize: 17,
    color: '#111',
  },
  notesInput: {
    height: 90,
    borderWidth: 1,
    borderColor: '#aaa',
    borderRadius: 9,
    backgroundColor: '#fff',
    padding: 12,
    fontSize: 15,
    color: '#111',
    textAlignVertical: 'top',
  },
  countText: {
    textAlign: 'right',
    color: '#555',
    marginTop: 8,
  },
  confirmButton: {
    height: 50,
    backgroundColor: '#0A84FF',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 30,
  },
  confirmText: {
    color: '#fff',
    fontSize: 19,
    fontWeight: '700',
  },
});